---
    #echo "{{item.name}} " $PW
    #ldapsearch -H ldaps://{{CERT_LDAP}}:636 -b "{{OLCSUFFIX}}" -x -D "{{OLCROOTDN}}" -w "{{OLCROOTPW}}"
    #ldapmodify -Q -Y EXTERNAL -H ldapi:///
    #ldapmodify -H 'ldap://doxer.org' -D 'cn=Manager,dc=test,dc=com' -w 'password'
    # ldapmodify -H ldaps://{{CERT_LDAP}}:636 -D dn -w password <<!
    # ldapmodify -H ldaps://{{CERT_LDAP}}:636 -b "{{OLCSUFFIX}}" -x -D "{{OLCROOTDN}}" -w "{{OLCROOTPW}}"  <<!

## update the users passwords.
- name: Encode and update user passwords inside LDAP
  shell: |
    export PW=`slappasswd -s {{item.pw}}`
    ldapmodify -H ldaps://{{CERT_LDAP}}:636  -x -D "{{OLCROOTDN}}" -w "{{OLCROOTPW}}"  <<_EOF_
    #dn: uid=user,dc=example,dc=com
    {% if item.tenant in ("users","", " ")  or item.tenant is not defined or multitenancy | bool == false %}
    dn: uid={{item.name}},ou=users,{{OLCSUFFIX}}
    {% else %}
    dn: uid={{item.name}},ou=users,ou={{item.tenant}},{{OLCSUFFIX}}
    {% endif %}
    changetype: modify
    replace: userPassword
    userPassword: $PW
    _EOF_
    exit 0
  with_items: "{{user_list}}"
  register: pass_update
  tags:
    - passchange
- debug: var=pass_update
  tags:
    - passchange
